TEAM_SPECTATOR = 1
TEAM_SURVIVOR = 2
TEAM_ZOMBIEMASTER = 3

REDUCED_CARRY_MASS = 1

AFK_PUNISH_NOTHING = 0
AFK_PUNISH_SPECTATE = 1
AFK_PUNISH_KICK = 2

DT_PLAYER_AND_ENTITY_INT_COLLISION_FLAG = 18
DT_PLAYER_AND_ENTITY_INT_COLLISION_GROUP = 19

COLOR_GRAY = Color(190, 190, 190)
COLOR_RED = Color(255, 0, 0)
COLOR_BLUE = Color(0, 0, 255)
COLOR_GREEN = Color(0, 255, 0)
COLOR_LIMEGREEN = Color(50, 255, 50)
COLOR_YELLOW = Color(255, 255, 0)
COLOR_CYAN = Color(0, 255, 255)
COLOR_WHITE = Color(255, 255, 255)
COLOR_PURPLE = Color(255, 0, 255)
COLOR_PINK = Color(255, 20, 100)
COLOR_ORANGE = Color(255, 200, 0)
COLOR_BROWN = Color(168, 94, 0)
COLOR_TAN = Color(204, 195, 43)
COLOR_LBLUE = Color(25, 50, 255)
COLOR_SOFTRED = Color(255, 40, 40)

COLOR_RPURPLE = Color(200, 0, 200)
COLOR_RPINK = Color(255, 100, 255)
COLOR_RORANGE = Color(255, 128, 0)

COLOR_SALMON = Color(250, 98, 84)
COLOR_BRASS = Color(241, 184, 45)
COLOR_LEMONLIME = Color(227, 255, 0)
COLOR_GLIME = Color(158, 253, 56)
COLOR_SEAGREEN = Color(62, 178, 170)
COLOR_SLATEBLUE = Color(106, 130, 205)
COLOR_LVIOLET = Color(205, 178, 229)
COLOR_CERISE = Color(199, 152, 252)
COLOR_TURQ = Color(125, 228, 125)
COLOR_RUST = Color(185, 118, 90)
COLOR_SOFTBLUE = Color(193, 255, 255)

COLOR_DARKGRAY = Color(40, 40, 40)
COLOR_DARKRED = Color(185, 35, 35)
COLOR_DARKGREEN = Color(0, 150, 0)
COLOR_DARKBLUE = Color(5, 75, 150)

COLOR_MIDGRAY = Color(140, 140, 140)
COLOR_NEARGRAY = Color(222, 222, 222)

COLOR_FRIENDLY = COLOR_DARKGREEN
COLOR_HEALTHY = COLOR_DARKGREEN
COLOR_SCRATCHED = Color(90, 170, 0)
COLOR_HURT = Color(150, 50, 0)
COLOR_CRITICAL = COLOR_DARKRED

local PowIndex
local function GetNextPow( i )
	if i then PowIndex = i end
	local r = PowIndex
	PowIndex = bit.lshift(PowIndex,1)
	return r
end
local function GetNextIndex( i )
	if i then PowIndex = i end
	local r = PowIndex
	PowIndex = PowIndex+1
	return r
end

ZS_COLLISIONGROUP_DEFAULT = 0
ZS_COLLISIONGROUP_NONE = GetNextPow(1)
ZS_COLLISIONGROUP_ALL = GetNextPow()
ZS_COLLISIONGROUP_PROP = GetNextPow()
ZS_COLLISIONGROUP_AMMO = GetNextPow()
ZS_COLLISIONGROUP_HUMAN = GetNextPow()
ZS_COLLISIONGROUP_ITEMCRATE = GetNextPow()

ZS_COLLISIONFLAGS_HUMAN = bit.bor(ZS_COLLISIONGROUP_ALL, ZS_COLLISIONGROUP_PROP, ZS_COLLISIONGROUP_ITEMCRATE)
ZS_COLLISIONFLAGS_HUMAN_COLLIDE_OTHER_HUMAN = bit.bor(ZS_COLLISIONGROUP_HUMAN, ZS_COLLISIONGROUP_ALL, ZS_COLLISIONGROUP_PROP, ZS_COLLISIONGROUP_ITEMCRATE)
ZS_COLLISIONFLAGS_PROP = bit.bor(ZS_COLLISIONGROUP_ALL, ZS_COLLISIONGROUP_PROP, ZS_COLLISIONGROUP_AMMO)
ZS_COLLISIONFLAGS_AMMO = bit.bor(ZS_COLLISIONGROUP_ALL, ZS_COLLISIONGROUP_PROP, ZS_COLLISIONGROUP_HUMAN)
ZS_COLLISIONFLAGS_ITEMCRATE = bit.bor(ZS_COLLISIONGROUP_ALL, ZS_COLLISIONGROUP_PROP)

FCAP_MUST_SPAWN = 0x00000001
FCAP_ACROSS_TRANSITION = 0x00000002
FCAP_FORCE_TRANSITION = 0x00000004
FCAP_NOTIFY_ON_TRANSITION = 0x00000008

FCAP_IMPULSE_USE = 0x00000010
FCAP_CONTINUOUS_USE = 0x00000020
FCAP_ONOFF_USE = 0x00000040
FCAP_DIRECTIONAL_USE = 0x00000080

FCAP_USE_ONGROUND = 0x00000100
FCAP_USE_IN_RADIUS = 0x00000200
FCAP_SAVE_NON_NETWORKABLE = 0x00000400

FCAP_MASTER = 0x10000000
FCAP_WCEDIT_POSITION = 0x40000000
FCAP_DONT_SAVE = 0x80000000

ZM_PHYSEXP_DAMAGE = 17500
ZM_PHYSEXP_RADIUS = 222
ZM_PHYSEXP_DELAY = 7.4

SCROLL_THRESHOLD = 8

FL_SPAWN_SHAMBLER_ALLOWED = GetNextPow(1)
FL_SPAWN_BANSHEE_ALLOWED = GetNextPow()
FL_SPAWN_HULK_ALLOWED = GetNextPow()
FL_SPAWN_DRIFTER_ALLOWED = GetNextPow()
FL_SPAWN_IMMOLATOR_ALLOWED = GetNextPow()

SF_PHYSEXPLOSION_NODAMAGE = 0x0001
SF_PHYSEXPLOSION_PUSH_PLAYER = 0x0002
SF_PHYSEXPLOSION_RADIAL = 0x0004
SF_PHYSEXPLOSION_TEST_LOS = 0x0008
SF_PHYSEXPLOSION_DISORIENT_PLAYER = 0x0010

SF_ZOMBIE_WANDER_ON_IDLE = 32

ZOMBIE_BUCKSHOT_TRIPLE_DAMAGE_DIST = 96

HUD_DEFAULT = 0
HUD_ZMR = 1

VECTOR_CONE_0DEGREES = Vector( 0.00218, 0.00218, 0.00218 )
VECTOR_CONE_1DEGREES = Vector( 0.00873, 0.00873, 0.00873 )
VECTOR_CONE_2DEGREES = Vector( 0.01745, 0.01745, 0.01745 )
VECTOR_CONE_3DEGREES = Vector( 0.02618, 0.02618, 0.02618 )
VECTOR_CONE_4DEGREES = Vector( 0.03490, 0.03490, 0.03490 )
VECTOR_CONE_5DEGREES = Vector( 0.04362, 0.04362, 0.04362 )
VECTOR_CONE_6DEGREES = Vector( 0.05234, 0.05234, 0.05234 )
VECTOR_CONE_7DEGREES = Vector( 0.06105, 0.06105, 0.06105 )
VECTOR_CONE_8DEGREES = Vector( 0.06976, 0.06976, 0.06976 )
VECTOR_CONE_9DEGREES = Vector( 0.07846, 0.07846, 0.07846 )
VECTOR_CONE_10DEGREES = Vector( 0.08716, 0.08716, 0.08716 )
VECTOR_CONE_15DEGREES = Vector( 0.13053, 0.13053, 0.13053 )
VECTOR_CONE_20DEGREES = Vector( 0.17365, 0.17365, 0.17365 )

COND_NONE = 0
COND_IN_PVS = GetNextIndex(1)
COND_IDLE_INTERRUPT = GetNextIndex()
COND_LOW_PRIMARY_AMMO = GetNextIndex()
COND_NO_PRIMARY_AMMO = GetNextIndex()
COND_NO_SECONDARY_AMMO = GetNextIndex()
COND_NO_WEAPON = GetNextIndex()
COND_SEE_HATE = GetNextIndex()
COND_SEE_FEAR = GetNextIndex()
COND_SEE_DISLIKE = GetNextIndex()
COND_SEE_ENEMY = GetNextIndex()
COND_LOST_ENEMY = GetNextIndex()
COND_ENEMY_WENT_NULL = GetNextIndex()
COND_ENEMY_OCCLUDED = GetNextIndex()
COND_TARGET_OCCLUDED = GetNextIndex()
COND_HAVE_ENEMY_LOS = GetNextIndex()
COND_HAVE_TARGET_LOS = GetNextIndex()
COND_LIGHT_DAMAGE = GetNextIndex()
COND_HEAVY_DAMAGE = GetNextIndex()
COND_PHYSICS_DAMAGE = GetNextIndex()
COND_REPEATED_DAMAGE = GetNextIndex()
COND_CAN_RANGE_ATTACK1 = GetNextIndex()
COND_CAN_RANGE_ATTACK2 = GetNextIndex()
COND_CAN_MELEE_ATTACK1 = GetNextIndex()
COND_CAN_MELEE_ATTACK2 = GetNextIndex()
COND_PROVOKED = GetNextIndex()
COND_NEW_ENEMY = GetNextIndex()
COND_ENEMY_TOO_FAR = GetNextIndex()
COND_ENEMY_FACING_ME = GetNextIndex()
COND_BEHIND_ENEMY = GetNextIndex()
COND_ENEMY_DEAD = GetNextIndex()
COND_ENEMY_UNREACHABLE = GetNextIndex()
COND_SEE_PLAYER = GetNextIndex()
COND_LOST_PLAYER = GetNextIndex()
COND_SEE_NEMESIS = GetNextIndex()
COND_TASK_FAILED = GetNextIndex()
COND_SCHEDULE_DONE = GetNextIndex()
COND_SMELL = GetNextIndex()
COND_TOO_CLOSE_TO_ATTACK = GetNextIndex()
COND_TOO_FAR_TO_ATTACK = GetNextIndex()
COND_NOT_FACING_ATTACK = GetNextIndex()
COND_WEAPON_HAS_LOS = GetNextIndex()
COND_WEAPON_BLOCKED_BY_FRIEND = GetNextIndex()
COND_WEAPON_PLAYER_IN_SPREAD = GetNextIndex()
COND_WEAPON_PLAYER_NEAR_TARGET = GetNextIndex()
COND_WEAPON_SIGHT_OCCLUDED = GetNextIndex()
COND_BETTER_WEAPON_AVAILABLE = GetNextIndex()
COND_HEALTH_ITEM_AVAILABLE = GetNextIndex()
COND_GIVE_WAY = GetNextIndex()
COND_WAY_CLEAR = GetNextIndex()
COND_HEAR_DANGER = GetNextIndex()
COND_HEAR_THUMPER = GetNextIndex()
COND_HEAR_BUGBAIT = GetNextIndex()
COND_HEAR_COMBAT = GetNextIndex()
COND_HEAR_WORLD = GetNextIndex()
COND_HEAR_PLAYER = GetNextIndex()
COND_HEAR_BULLET_IMPACT = GetNextIndex()
COND_HEAR_PHYSICS_DANGER = GetNextIndex()
COND_HEAR_MOVE_AWAY = GetNextIndex()
COND_HEAR_SPOOKY = GetNextIndex()
COND_NO_HEAR_DANGER = GetNextIndex()
COND_FLOATING_OFF_GROUND = GetNextIndex()
COND_MOBBED_BY_ENEMIES = GetNextIndex()
COND_RECEIVED_ORDERS = GetNextIndex()
COND_PLAYER_ADDED_TO_SQUAD = GetNextIndex()
COND_PLAYER_REMOVED_FROM_SQUAD = GetNextIndex()
COND_PLAYER_PUSHING = GetNextIndex()
COND_NPC_FREEZE = GetNextIndex()
COND_NPC_UNFREEZE = GetNextIndex()
COND_TALKER_RESPOND_TO_QUESTION = GetNextIndex()
COND_NO_CUSTOM_INTERRUPTS = GetNextIndex()

AE_ZOMBIE_ATTACK_RIGHT = 45
AE_ZOMBIE_ATTACK_LEFT = 46
AE_ZOMBIE_ATTACK_BOTH = 47
AE_ZOMBIE_SWATITEM = 48
AE_ZOMBIE_STARTSWAT = 49
AE_ZOMBIE_STEP_LEFT = 50
AE_ZOMBIE_STEP_RIGHT = 51
AE_ZOMBIE_SCUFF_LEFT = 52
AE_ZOMBIE_SCUFF_RIGHT = 53
AE_ZOMBIE_ATTACK_SCREAM = 54
AE_ZOMBIE_GET_UP = 55
AE_ZOMBIE_POUND = 56
AE_ZOMBIE_ALERTSOUND = 57
AE_ZOMBIE_POPHEADCRAB = 58

HUMAN_WIN_SCORE = 50
HUMAN_LOSS_SCORE = 50

GM.AmmoClass = {}
GM.AmmoClass["item_ammo_357"] = "357"
GM.AmmoClass["item_ammo_357_large"] = "357_large"
GM.AmmoClass["item_ammo_pistol"] = "pistol"
GM.AmmoClass["item_ammo_pistol_large"] = "pistol_large"
GM.AmmoClass["item_ammo_ar2"] = "ar2"
GM.AmmoClass["item_ammo_ar2_large"] = "ar2_large"
GM.AmmoClass["item_ammo_smg1"] = "smg1"
GM.AmmoClass["item_ammo_smg1_large"] = "smg1_large"
GM.AmmoClass["item_box_buckshot"] = "buckshot"
GM.AmmoClass["item_ammo_revolver"] = "revolver"
GM.AmmoClass["weapon_zm_molotov"] = "molotov"

GM.AmmoCache = {}
GM.AmmoCache["pistol"] = 20
GM.AmmoCache["pistol_large"] = 100
GM.AmmoCache["smg1"] = 30
GM.AmmoCache["smg1_large"] = 180
GM.AmmoCache["ar2"] = 20
GM.AmmoCache["ar2_large"] = 100
GM.AmmoCache["357"] = 11
GM.AmmoCache["357_large"] = 20
GM.AmmoCache["buckshot"] = 20
GM.AmmoCache["revolver"] = 6
GM.AmmoCache["molotov"] = 1

GM.AmmoModels = {}
GM.AmmoModels["item_ammo_revolver"] = "models/items/revolverammo.mdl"
GM.AmmoModels["item_ammo_smg1"] = "models/items/boxmrounds.mdl"
GM.AmmoModels["item_ammo_smg1_large"] = "models/items/boxmrounds.mdl"
GM.AmmoModels["item_ammo_357"] = "models/items/357ammo.mdl"
GM.AmmoModels["item_ammo_357_large"] = "models/items/357ammo.mdl"
GM.AmmoModels["item_ammo_pistol"] = "models/items/boxsrounds.mdl"
GM.AmmoModels["item_ammo_pistol_large"] = "models/items/boxsrounds.mdl"
GM.AmmoModels["item_box_buckshot"] = "models/items/boxbuckshot.mdl"

CARRY_MASS = 40
CARRY_VOLUME = 256

GM.HumanGibs = {
    Model("models/gibs/HGIBS.mdl"),
    Model("models/gibs/HGIBS_spine.mdl"),

    Model("models/gibs/HGIBS_rib.mdl"),
    Model("models/gibs/HGIBS_scapula.mdl"),
    Model("models/gibs/antlion_gib_medium_2.mdl"),
    Model("models/gibs/Antlion_gib_Large_1.mdl"),
    Model("models/gibs/Strider_Gib4.mdl")
}

GM.CleanupFilterServer = {
	"zm_hands"
}

GM.CleanupFilterClient = {
    "zm_hands",
    "env_fire", 
    "entityflame", 
    "_firesmoke"
}